networks:
  aprilrain_queue_network:
    driver: bridge
  aprilrain_db_network:
    driver: bridge
  # ============================
  # Database (mongodb)
  # ============================
services:
  mongodb:
    image: mongo
    container_name: mongodb
    hostname: mongodb
    restart: always
    #ports:
    #  - "27017:27017"
    volumes:
      - aprilrain_mongodb_data:/data/db
      - ~/Belgeler/mongodb_data:/tmp/dump
    env_file:
      - ~/Belgeler/app_environment/mongo.env
    networks:
      - aprilrain_queue_network
      - aprilrain_db_network 
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 2m
      timeout: 10s
      retries: 3

  # ============================
  # Mongo-Express 
  # ============================
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    hostname: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - ~/Belgeler/app_environment/mongo.env
    networks:
      - aprilrain_db_network 
    depends_on:
      - mongodb

