networks:
  aprilrain_queue_network:
    driver: bridge
  aprilrain_db_network:
    driver: bridge

volumes:
  aprilrain_mongodb_data:  # Docker volume tanımı

  # ============================
  # Database (mongodb)
  # ============================
mongodb:
  image: mongo
  container_name: mongodb
  hostname: mongodb
  restart: always
  #ports:
  #  - "27017:27017"
  volumes:
    - aprilrain_mongodb_data:/data/db
    - /home/helis/Documents/app_data/helis_mongo_data:/data/db
    - /home/helis/Documents/app_data/aprilrain_dump:/tmp/dump
    env_file:
      - ~/Documents/app_environment/mongo.env
  networks:
    - aprilrain_queue_network
    - aprilrain_db_network
  healthcheck:
    test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
    interval: 2m
    timeout: 10s
    retries: 3

 
